In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline
from sklearn.metrics import accuracy_score
import time

In [ ]:
train = pd.read_csv('/content/drive/My Drive/HTC_CNN_dataset/WOS/wos_train_final.csv')
test = pd.read_csv('/content/drive/My Drive/HTC_CNN_dataset/WOS/wos_test_final.csv')

In [ ]:
train_data = train
test_data = test

tfidf = TfidfVectorizer()

In [ ]:
train.head()

,text,l1,l2
0,(beta-amyloid (A beta) and tau pathology becom...,Medical,Alzheimers-Disease
1,(D)ecreasing of energy consumption and environ...,Civil,Green-Building
2,(Hybrid) electric vehicles are assumed to play...,ECE,Electric-motor
3,(R)ecent advances in deep brain stimulators an...,biochemistry,Molecular-biology
4,(T)his paper presents the concept of a softwar...,ECE,Satellite-radio

In [ ]:
test.head()

,text,l1,l2
0,(2 + 1)-dimensional non-linear optical waves t...,CS,Symbolic-computation
1,"(L)-3,4-Dihydroxyphenylalanine ((L)-DOPA) rema...",Medical,Parkinsons-Disease
2,(Objective) In order to increase classificatio...,CS,Computer-vision
3,. Background: A key feature of factorIXa is it...,biochemistry,Enzymology
4,. Haemophilia A (HA) is caused by widespread m...,biochemistry,Southern-blotting

In [ ]:
X_train_text = train_data['text'].values
y_train_l1 = train_data['l1'].values
y_train_l2 = train_data['l2'].values

X_test_text = test_data['text'].values
y_test_l1 = test_data['l1'].values
y_test_l2 = test_data['l2'].values

In [ ]:
start_time = time.time()
model_l1 = make_pipeline(TfidfVectorizer(), LogisticRegression())
model_l1.fit(X_train_text, y_train_l1)
end_time = time.time()
time_l1 = round(end_time - start_time)
print(f'Time for l1: {time_l1}')

accuracy_l1 = accuracy_score(y_train_l1, model_l1.predict(X_train_text))
print(f'Level 1 Accuracy (Training Set): {accuracy_l1:.4f}')

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Time for l1: 39
训练集 l1 的准确率: 0.9048

In [ ]:
start_time = time.time()
model_l2 = make_pipeline(TfidfVectorizer(), LogisticRegression())
model_l2.fit(X_train_text, y_train_l2)
end_time = time.time()
time_l2 = round(end_time - start_time)
print(f'Time for l2: {time_l2}')

accuracy_l2 = accuracy_score(y_train_l2, model_l2.predict(X_train_text))
print(f'Level 2 Accuracy (Training Set): {accuracy_l2:.4f}')

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Time for l2: 451
训练集 l2 的准确率: 0.8315

In [ ]:
test_pred_l1 = model_l1.predict(X_test_text)
test_pred_l2 = model_l2.predict(X_test_text)

In [ ]:
test_accuracy_l1 = accuracy_score(y_test_l1, test_pred_l1)
test_accuracy_l2 = accuracy_score(y_test_l2, test_pred_l2)

In [ ]:
print(f'Test Accuracy for l1: {test_accuracy_l1:.4f}')
print(f'Test Accuracy for l2: {test_accuracy_l2:.4f}')

Test Accuracy for l1: 0.8273
Test Accuracy for l2: 0.6650

In [ ]:
import numpy as np

correct_l1 = test_pred_l1 == y_test_l1
accuracy_l1 = np.mean(correct_l1)
print(f"Consistency Accuracy for l1: {accuracy_l1:.4f}")


correct_l1_indices = np.where(correct_l1)[0]
pred_labels_l2_filtered = test_pred_l2[correct_l1_indices]
labels_l2_filtered = y_test_l2[correct_l1_indices]

correct_l2 = pred_labels_l2_filtered == labels_l2_filtered
accuracy_l2 = np.sum(correct_l2) / len(y_test_l2)
print(f"Consistency Accuracy for l2: {accuracy_l2:.4f}")

Consistency Accuracy for l1: 0.8273
Consistency Accuracy for l2: 0.6048